# **Aula 08** - Biblioteca Pandas

16-092026

Para que todas as soluções propostas funcionem vamos seguir algumas regras:
* Mantenha as primeira duas células inalteradas;
* Crie cópias do dataset principal para as soluções;
* Use comentários para explicar a solução proposta;
* Insira seu nome na solução;
* A terceira célula é exemplo de como inserir.

# Importando o pandas (não altere)

In [2]:
import pandas as pd

# Criando um dataset importando um arquivo csv (não altere).

O arquivo *clima_historico_municipal.csv* contém um registro por município, identificado por código IBGE, nome e UF. Para cada município, a base informa o período de referência, a fonte climática, o método de processamento e um conjunto de variáveis mensais agregadas historicamente. As variáveis climáticas presentes são:

* tmin_*: temperatura mínima média mensal histórica
* tmax_*: temperatura máxima média mensal histórica
* temp_media_*: temperatura média mensal histórica, derivada de * tmin e tmax
* ppt_*: precipitação mensal histórica
* pet_*: evapotranspiração potencial mensal histórica
* aet_*: evapotranspiração real mensal histórica
* def_*: déficit hídrico mensal histórico

Cada sufixo mensal corresponde a um mês do ano:

*jan, fev, mar, abr, mai, jun, jul, ago, set, out, nov, dez*

Assim, por exemplo:

* temp_media_jan representa a média histórica de temperatura média para todos os janeiros do período processado
* ppt_mar representa a média histórica de precipitação para todos os meses de março do período processado
* def_set representa a média histórica de déficit hídrico para todos os meses de setembro do período processado

As unidades utilizadas são:
* temperaturas (*tmin, tmax, temp_media*): **graus Celsius (°C)**
* precipitação (*ppt*): **milímetros por mês (mm/mês)**
* evapotranspiração potencial (*pet*): **milímetros por mês (mm/mês)**
* evapotranspiração real (*aet*): **milímetros por mês (mm/mês)**
* déficit hídrico (*def*): **milímetros por mês (mm/mês)**

In [5]:
#Importando um arquivo .csv dos dados de temperatura dos municípios
df = pd.read_csv('https://raw.githubusercontent.com/andr3nf/clima_municipios_brasileiros/refs/heads/main/clima_historico_municipal.csv')

# Comandos para visualização geral dos dados

In [6]:
'''
Chamar apenas o dataframe para visualização, usa-se o nome do dataframe, neste caso o df
Quando o dataframe é muito grande ele apresenta as primeiras e últimas 5 linhas
Info: Gerson Battisti
'''
# visualiza todo DataFrame
df

,codigo_ibge,nome_municipio,uf,periodo_inicio,periodo_fim,fonte_clima,metodo_processamento,temp_media_jan,temp_media_fev,temp_media_mar,...,def_mar,def_abr,def_mai,def_jun,def_jul,def_ago,def_set,def_out,def_nov,def_dez
0,1100015,Alta Floresta D'Oeste,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.18,25.23,25.57,...,0.00,2.45,14.87,31.74,50.42,64.80,46.20,11.53,2.90,0.29
1,1100023,Ariquemes,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.29,25.39,25.59,...,0.00,0.29,5.65,29.46,46.09,53.95,19.80,1.41,0.06,0.00
2,1100031,Cabixi,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.85,25.80,26.13,...,0.00,1.65,16.77,31.91,49.42,67.96,55.16,10.79,4.60,0.04
3,1100049,Cacoal,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,24.69,24.84,25.18,...,0.00,0.44,14.36,31.44,48.04,60.16,29.09,5.23,1.08,0.00
4,1100056,Cerejeiras,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.84,25.82,26.18,...,0.00,2.67,17.16,33.05,53.29,74.58,60.96,11.31,4.35,0.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5565,5222005,Vianópolis,GO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,22.55,22.67,22.73,...,2.36,9.14,31.73,50.22,79.46,103.54,92.59,35.55,3.85,0.01
5566,5222054,Vicentinópolis,GO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,24.23,24.62,24.66,...,2.39,11.55,36.91,58.97,84.52,110.33,91.72,33.09,5.48,0.00
5567,5222203,Vila Boa,GO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,24.73,24.74,24.75,...,7.63,14.68,44.94,63.04,91.81,113.21,104.04,52.02,7.87,6.10
5568,5222302,Vila Propício,GO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,24.02,24.16,24.18,...,4.17,10.77,37.17,55.68,85.60,115.28,95.54,38.63,2.24,2.53
5569,5300108,Brasília,DF,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,21.88,22.00,21.92,...,3.09,8.42,31.06,46.80,74.12,99.77,91.04,40.31,2.58,0.83

# Comandos para visualização parcial dos dados
Visualição rápida, mas não total, das informações

In [15]:
'''
Comandos para visualização PARCIAL dos dados (não mostra tudo de uma vez).
head(n)   -> mostra as n primeiras linhas do dataframe (padrão: 5)
tail(n)   -> mostra as n últimas linhas do dataframe (padrão: 5)
sample(n) -> mostra n linhas escolhidas aleatoriamente
Info: Gabriel
'''

# Mostra as 5 primeiras linhas do dataframe
display(df.head())

# Mostra as 5 últimas linhas do dataframe
display(df.tail())

# Mostra 5 linhas aleatórias do dataframe
display(df.sample(5))

,codigo_ibge,nome_municipio,uf,periodo_inicio,periodo_fim,fonte_clima,metodo_processamento,temp_media_jan,temp_media_fev,temp_media_mar,...,def_mar,def_abr,def_mai,def_jun,def_jul,def_ago,def_set,def_out,def_nov,def_dez
0,1100015,Alta Floresta D'Oeste,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.18,25.23,25.57,...,0.0,2.45,14.87,31.74,50.42,64.80,46.20,11.53,2.90,0.29
1,1100023,Ariquemes,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.29,25.39,25.59,...,0.0,0.29,5.65,29.46,46.09,53.95,19.80,1.41,0.06,0.00
2,1100031,Cabixi,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.85,25.80,26.13,...,0.0,1.65,16.77,31.91,49.42,67.96,55.16,10.79,4.60,0.04
3,1100049,Cacoal,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,24.69,24.84,25.18,...,0.0,0.44,14.36,31.44,48.04,60.16,29.09,5.23,1.08,0.00
4,1100056,Cerejeiras,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.84,25.82,26.18,...,0.0,2.67,17.16,33.05,53.29,74.58,60.96,11.31,4.35,0.36

,codigo_ibge,nome_municipio,uf,periodo_inicio,periodo_fim,fonte_clima,metodo_processamento,temp_media_jan,temp_media_fev,temp_media_mar,...,def_mar,def_abr,def_mai,def_jun,def_jul,def_ago,def_set,def_out,def_nov,def_dez
5565,5222005,Vianópolis,GO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,22.55,22.67,22.73,...,2.36,9.14,31.73,50.22,79.46,103.54,92.59,35.55,3.85,0.01
5566,5222054,Vicentinópolis,GO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,24.23,24.62,24.66,...,2.39,11.55,36.91,58.97,84.52,110.33,91.72,33.09,5.48,0.00
5567,5222203,Vila Boa,GO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,24.73,24.74,24.75,...,7.63,14.68,44.94,63.04,91.81,113.21,104.04,52.02,7.87,6.10
5568,5222302,Vila Propício,GO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,24.02,24.16,24.18,...,4.17,10.77,37.17,55.68,85.60,115.28,95.54,38.63,2.24,2.53
5569,5300108,Brasília,DF,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,21.88,22.00,21.92,...,3.09,8.42,31.06,46.80,74.12,99.77,91.04,40.31,2.58,0.83

,codigo_ibge,nome_municipio,uf,periodo_inicio,periodo_fim,fonte_clima,metodo_processamento,temp_media_jan,temp_media_fev,temp_media_mar,...,def_mar,def_abr,def_mai,def_jun,def_jul,def_ago,def_set,def_out,def_nov,def_dez
3527,3522703,Itápolis,SP,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,24.68,24.66,24.23,...,8.95,40.03,49.47,51.01,67.43,94.19,84.67,44.00,20.67,8.53
4430,4207759,Iraceminha,SC,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,23.92,23.79,22.49,...,12.47,7.25,1.61,0.23,1.09,5.04,4.36,3.19,12.73,14.85
984,2306900,Jaguaribe,CE,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,28.27,27.65,27.12,...,13.59,18.42,34.72,53.82,84.21,129.23,147.06,160.69,148.50,129.12
960,2305209,Hidrolândia,CE,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,27.02,26.48,25.71,...,7.14,8.28,23.07,47.75,87.85,132.99,145.24,151.87,138.13,117.70
1910,2906857,Capela do Alto Alegre,BA,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.76,25.80,25.50,...,64.32,45.86,38.49,23.64,36.97,65.26,86.33,101.92,72.49,75.03

# Como saber a quantidade de linhas e colunas do dataframe

In [10]:
'''
Comandos para saber o tamanho (dimensões) do dataframe.
shape -> retorna uma tupla (quantidade_de_linhas, quantidade_de_colunas)
len() -> retorna apenas a quantidade de linhas
Info: Gabriel
'''

# shape é um atributo (sem parênteses) que retorna (linhas, colunas)
print('Formato (linhas, colunas):', df.shape)

# Podemos acessar cada valor da tupla separadamente
print('Linhas:', df.shape[0])
print('Colunas:', df.shape[1])

# len() também retorna a quantidade de linhas do dataframe
print('Linhas (len):', len(df))

Formato (linhas, colunas): (5570, 91)
Linhas: 5570
Colunas: 91
Linhas (len): 5570

# Como renomear o nome das colunas

In [17]:
'''
Comandos para renomear o nome das colunas do dataframe.
rename(columns={...}) -> renomeia colunas específicas, passando um dicionário
                          no formato {'nome_antigo': 'nome_novo'}
columns = [...] -> substitui TODOS os nomes das colunas de uma vez (lista completa)
Info: Gabriel
'''

# Sempre trabalhamos em uma cópia do dataframe original, para não alterar o df principal
df_renomeado = df.copy()

# Renomeia apenas as colunas indicadas, usando um dicionário {nome_atual: nome_novo}
df_renomeado = df_renomeado.rename(columns={
    'codigo_ibge': 'COD_IBGE',
    'nome_municipio': 'municipio',
    'uf': 'estado'
})

# Confirma que os nomes foram alterados
display(df_renomeado.head())

,COD_IBGE,municipio,estado,periodo_inicio,periodo_fim,fonte_clima,metodo_processamento,temp_media_jan,temp_media_fev,temp_media_mar,...,def_mar,def_abr,def_mai,def_jun,def_jul,def_ago,def_set,def_out,def_nov,def_dez
0,1100015,Alta Floresta D'Oeste,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.18,25.23,25.57,...,0.0,2.45,14.87,31.74,50.42,64.80,46.20,11.53,2.90,0.29
1,1100023,Ariquemes,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.29,25.39,25.59,...,0.0,0.29,5.65,29.46,46.09,53.95,19.80,1.41,0.06,0.00
2,1100031,Cabixi,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.85,25.80,26.13,...,0.0,1.65,16.77,31.91,49.42,67.96,55.16,10.79,4.60,0.04
3,1100049,Cacoal,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,24.69,24.84,25.18,...,0.0,0.44,14.36,31.44,48.04,60.16,29.09,5.23,1.08,0.00
4,1100056,Cerejeiras,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.84,25.82,26.18,...,0.0,2.67,17.16,33.05,53.29,74.58,60.96,11.31,4.35,0.36

# Como adicionar linhas ao dataframe

In [18]:
'''
Comandos para adicionar linhas ao dataframe.
pd.concat([df1, df2]) -> junta (empilha) dois dataframes, um embaixo do outro
ignore_index=True -> refaz o índice (0, 1, 2, ...) em vez de repetir índices antigos
Info: Gabriel
'''

# Trabalhamos em uma cópia do dataframe original
df_add = df.copy()

# Cria a nova linha como um dataframe de uma única linha.
# Não precisamos preencher todas as 91 colunas: as que não citarmos
# ficarão automaticamente com valor NaN (vazio) na linha nova.
nova_linha = pd.DataFrame([{
    'codigo_ibge': 9999999,
    'nome_municipio': 'Cidade Exemplo',
    'uf': 'XX',
    'periodo_inicio': 1975,
    'periodo_fim': 2024
}])

# pd.concat empilha os dois dataframes (df_add + nova_linha)
# ignore_index=True evita que o índice da nova linha se repita (fica 0 igual ao original)
df_add = pd.concat([df_add, nova_linha], ignore_index=True)

# Mostra as últimas linhas para conferir que a linha nova foi adicionada ao final
display(df_add.tail())

,codigo_ibge,nome_municipio,uf,periodo_inicio,periodo_fim,fonte_clima,metodo_processamento,temp_media_jan,temp_media_fev,temp_media_mar,...,def_mar,def_abr,def_mai,def_jun,def_jul,def_ago,def_set,def_out,def_nov,def_dez
5566,5222054,Vicentinópolis,GO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,24.23,24.62,24.66,...,2.39,11.55,36.91,58.97,84.52,110.33,91.72,33.09,5.48,0.00
5567,5222203,Vila Boa,GO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,24.73,24.74,24.75,...,7.63,14.68,44.94,63.04,91.81,113.21,104.04,52.02,7.87,6.10
5568,5222302,Vila Propício,GO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,24.02,24.16,24.18,...,4.17,10.77,37.17,55.68,85.60,115.28,95.54,38.63,2.24,2.53
5569,5300108,Brasília,DF,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,21.88,22.00,21.92,...,3.09,8.42,31.06,46.80,74.12,99.77,91.04,40.31,2.58,0.83
5570,9999999,Cidade Exemplo,XX,1975,2024,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Como adicionar colunas ao dataframe

In [19]:
'''
Comandos para adicionar colunas ao dataframe.
df['nova_coluna'] = valor -> cria uma coluna nova (valor único ou calculado)
insert(posicao, nome, valores) -> cria a coluna em uma posição específica
Info: Gabriel
'''

# Trabalhamos em uma cópia do dataframe original
df_col = df.copy()

# Forma 1: coluna com um valor fixo, repetido em todas as linhas
df_col['pais'] = 'Brasil'

# Forma 2: coluna calculada a partir de outras colunas (operação é feita linha a linha)
# Aqui calculamos a amplitude térmica de janeiro (diferença entre máxima e mínima)
df_col['amplitude_termica_jan'] = df_col['tmax_jan'] - df_col['tmin_jan']

# Forma 3: insert() permite escolher a posição (índice) onde a coluna vai aparecer
# Aqui inserimos 'pais' como a primeira coluna (posição 0)
df_col.insert(0, 'pais_destaque', df_col['pais'])

# Confirma as novas colunas
display(df_col.head())

,pais_destaque,codigo_ibge,nome_municipio,uf,periodo_inicio,periodo_fim,fonte_clima,metodo_processamento,temp_media_jan,temp_media_fev,...,def_mai,def_jun,def_jul,def_ago,def_set,def_out,def_nov,def_dez,pais,amplitude_termica_jan
0,Brasil,1100015,Alta Floresta D'Oeste,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.18,25.23,...,14.87,31.74,50.42,64.80,46.20,11.53,2.90,0.29,Brasil,10.68
1,Brasil,1100023,Ariquemes,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.29,25.39,...,5.65,29.46,46.09,53.95,19.80,1.41,0.06,0.00,Brasil,9.58
2,Brasil,1100031,Cabixi,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.85,25.80,...,16.77,31.91,49.42,67.96,55.16,10.79,4.60,0.04,Brasil,10.20
3,Brasil,1100049,Cacoal,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,24.69,24.84,...,14.36,31.44,48.04,60.16,29.09,5.23,1.08,0.00,Brasil,10.76
4,Brasil,1100056,Cerejeiras,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.84,25.82,...,17.16,33.05,53.29,74.58,60.96,11.31,4.35,0.36,Brasil,10.30

# Como deletar linhas

In [20]:
'''
Comandos para deletar linhas do dataframe.
drop(index=[...]) -> remove linhas específicas, pelo número do índice
df[condição] -> forma alternativa: mantém só as linhas que atendem a condição
                (ou seja, 'deleta' as que não atendem)
Info: Gabriel
'''

# Trabalhamos em uma cópia do dataframe original
df_del = df.copy()

# Forma 1: dropar linhas pelo índice (aqui removemos as linhas 0, 1 e 2)
df_del = df_del.drop(index=[0, 1, 2])
print('Linhas após remover pelo índice:', df_del.shape[0])

# Forma 2: 'deletar' linhas mantendo apenas as que atendem a uma condição
# Aqui mantemos só os municípios que NÃO são de Rondônia (uf diferente de 'RO')
df_del = df_del[df_del['uf'] != 'RO']
print('Linhas após remover municípios de RO:', df_del.shape[0])

display(df_del.head())

Linhas após remover pelo índice: 5567
Linhas após remover municípios de RO: 5518

,codigo_ibge,nome_municipio,uf,periodo_inicio,periodo_fim,fonte_clima,metodo_processamento,temp_media_jan,temp_media_fev,temp_media_mar,...,def_mar,def_abr,def_mai,def_jun,def_jul,def_ago,def_set,def_out,def_nov,def_dez
52,1200013,Acrelândia,AC,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,26.27,26.20,26.37,...,0.0,0.26,5.16,21.73,35.59,38.94,17.46,3.93,0.32,0.0
53,1200054,Assis Brasil,AC,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.68,25.36,25.31,...,0.0,0.18,6.16,22.91,32.02,38.24,23.28,4.19,0.00,0.0
54,1200104,Brasiléia,AC,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.92,25.54,25.52,...,0.0,0.33,7.74,25.53,34.94,43.43,26.08,4.85,0.04,0.0
55,1200138,Bujari,AC,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.60,25.49,25.56,...,0.0,0.27,4.41,12.01,24.42,27.57,12.74,2.32,0.18,0.0
56,1200179,Capixaba,AC,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,26.09,25.91,26.09,...,0.0,0.38,8.74,16.70,26.80,30.17,16.35,5.96,1.11,0.0

# Como deletar colunas

In [21]:
'''
Comandos para deletar colunas do dataframe.
drop(columns=[...]) -> remove uma ou mais colunas, pelo nome
drop([...], axis=1) -> forma equivalente, usando axis=1 para indicar 'colunas'
                        (axis=0 seria linhas, que é o padrão)
Info: Gabriel
'''

# Trabalhamos em uma cópia do dataframe original
df_col_del = df.copy()

# Forma 1: drop(columns=[...]) remove as colunas informadas pelo nome
df_col_del = df_col_del.drop(columns=['fonte_clima', 'metodo_processamento'])
print('Colunas após remover fonte_clima e metodo_processamento:', df_col_del.shape[1])

# Forma 2: mesmo resultado, usando axis=1 (1 = colunas, 0 = linhas)
df_col_del = df_col_del.drop(['periodo_inicio', 'periodo_fim'], axis=1)
print('Colunas após remover periodo_inicio e periodo_fim:', df_col_del.shape[1])

display(df_col_del.head())

Colunas após remover fonte_clima e metodo_processamento: 89
Colunas após remover periodo_inicio e periodo_fim: 87

,codigo_ibge,nome_municipio,uf,temp_media_jan,temp_media_fev,temp_media_mar,temp_media_abr,temp_media_mai,temp_media_jun,temp_media_jul,...,def_mar,def_abr,def_mai,def_jun,def_jul,def_ago,def_set,def_out,def_nov,def_dez
0,1100015,Alta Floresta D'Oeste,RO,25.18,25.23,25.57,25.26,24.39,23.66,23.90,...,0.0,2.45,14.87,31.74,50.42,64.80,46.20,11.53,2.90,0.29
1,1100023,Ariquemes,RO,25.29,25.39,25.59,25.54,25.24,24.71,24.91,...,0.0,0.29,5.65,29.46,46.09,53.95,19.80,1.41,0.06,0.00
2,1100031,Cabixi,RO,25.85,25.80,26.13,25.71,24.47,23.55,23.79,...,0.0,1.65,16.77,31.91,49.42,67.96,55.16,10.79,4.60,0.04
3,1100049,Cacoal,RO,24.69,24.84,25.18,24.87,24.46,23.73,24.00,...,0.0,0.44,14.36,31.44,48.04,60.16,29.09,5.23,1.08,0.00
4,1100056,Cerejeiras,RO,25.84,25.82,26.18,25.79,24.64,23.75,23.96,...,0.0,2.67,17.16,33.05,53.29,74.58,60.96,11.31,4.35,0.36

# Como mesclar dois dataframe

In [22]:
'''
Comandos para mesclar (juntar) dois dataframes.
pd.merge(df1, df2, on='coluna', how='left') -> junta as colunas de dois dataframes,
combinando as linhas que têm o mesmo valor na coluna informada em 'on'.
how define o tipo de junção: 'left', 'right', 'inner' ou 'outer'
Info: Gabriel
'''

# Trabalhamos em uma cópia do dataframe original
df_merge = df.copy()

# Cria um segundo dataframe pequeno, com a região de cada UF
df_regiao = pd.DataFrame({
    'uf': ['RO', 'GO', 'DF', 'SP', 'RS'],
    'regiao': ['Norte', 'Centro-Oeste', 'Centro-Oeste', 'Sudeste', 'Sul']
})

# pd.merge junta os dois dataframes usando a coluna 'uf' como referência
# how='left' mantém TODAS as linhas de df_merge, mesmo que a UF não esteja em df_regiao
# (nesse caso, a coluna 'regiao' fica como NaN para essas linhas)
df_merge = pd.merge(df_merge, df_regiao, on='uf', how='left')

# Mostra apenas algumas colunas para facilitar a conferência do resultado
display(df_merge[['nome_municipio', 'uf', 'regiao']].head())

          nome_municipio  uf regiao
0  Alta Floresta D'Oeste  RO  Norte
1              Ariquemes  RO  Norte
2                 Cabixi  RO  Norte
3                 Cacoal  RO  Norte
4             Cerejeiras  RO  Norte

# Buscar uma linha ou uma célula (linha e coluna) específica

In [23]:
'''
Comandos para buscar uma linha ou uma célula específica (linha + coluna).
loc[]  -> busca pelo RÓTULO (nome) do índice e da coluna
iloc[] -> busca pela POSIÇÃO numérica (como se fosse uma lista, começando em 0)
Info: Gabriel
'''

# Trabalhamos em uma cópia do dataframe original
df_busca = df.copy()

# Busca a linha de índice/rótulo 10 (retorna uma Series com todas as colunas dessa linha)
linha_loc = df_busca.loc[10]
display(linha_loc)

# Busca a linha pela POSIÇÃO 10 (11ª linha do dataframe, contando do zero)
linha_iloc = df_busca.iloc[10]
display(linha_iloc)

# Busca uma célula específica: linha de índice 10, coluna 'nome_municipio' (por rótulo)
celula_loc = df_busca.loc[10, 'nome_municipio']
print('Município (loc):', celula_loc)

# Busca a mesma célula por POSIÇÃO: linha 10, coluna 1 (segunda coluna do dataframe)
celula_iloc = df_busca.iloc[10, 1]
print('Município (iloc):', celula_iloc)

codigo_ibge       1100114
nome_municipio       Jaru
uf                     RO
periodo_inicio       1975
periodo_fim          2024
                   ...
def_ago             56.61
def_set             26.92
def_out              3.44
def_nov              0.74
def_dez               0.0
Name: 10, Length: 91, dtype: object

codigo_ibge       1100114
nome_municipio       Jaru
uf                     RO
periodo_inicio       1975
periodo_fim          2024
                   ...
def_ago             56.61
def_set             26.92
def_out              3.44
def_nov              0.74
def_dez               0.0
Name: 10, Length: 91, dtype: object

Município (loc): Jaru
Município (iloc): Jaru

# Buscar linhas de forma condicional

In [24]:
'''
Comandos para buscar linhas de forma condicional (filtros).
df[condição] -> mantém apenas as linhas onde a condição é True
&  -> 'E' lógico (as duas condições precisam ser verdadeiras)
|  -> 'OU' lógico (basta uma das condições ser verdadeira)
isin([...]) -> verifica se o valor está dentro de uma lista de opções
IMPORTANTE: cada condição entre parênteses ao combinar com & ou |
Info: Gabriel
'''

# Trabalhamos em uma cópia do dataframe original
df_cond = df.copy()

# Condição simples: municípios do estado do Rio Grande do Sul
rs = df_cond[df_cond['uf'] == 'RS']
print('Municípios do RS:', rs.shape[0])

# Condição composta com & (E): municípios do RS que tiveram temp_media_jan acima de 24°C
rs_quente = df_cond[(df_cond['uf'] == 'RS') & (df_cond['temp_media_jan'] > 24)]
display(rs_quente[['nome_municipio', 'uf', 'temp_media_jan']].head())

# Condição composta com | (OU): municípios do RS OU de SC
sul = df_cond[(df_cond['uf'] == 'RS') | (df_cond['uf'] == 'SC')]
print('Municípios do RS ou SC:', sul.shape[0])

# isin() é uma forma mais prática de comparar com VÁRIOS valores ao mesmo tempo
sul_isin = df_cond[df_cond['uf'].isin(['RS', 'SC', 'PR'])]
print('Municípios da região Sul (RS, SC, PR):', sul_isin.shape[0])

Municípios do RS: 497

     nome_municipio  uf  temp_media_jan
4606         Aceguá  RS           24.87
4608          Agudo  RS           24.33
4609      Ajuricaba  RS           24.38
4610        Alecrim  RS           25.87
4611       Alegrete  RS           25.26

Municípios do RS ou SC: 792
Municípios da região Sul (RS, SC, PR): 1191

# Buscar um dataframe parcial (Linhas e Colunas específicas)

In [25]:
'''
Comandos para buscar um dataframe PARCIAL (linhas e colunas específicas ao mesmo tempo).
loc[linhas, colunas]  -> seleciona por RÓTULO (nome do índice / nome das colunas)
iloc[linhas, colunas] -> seleciona por POSIÇÃO (números, começando em 0)
Info: Gabriel
'''

# Trabalhamos em uma cópia do dataframe original
df_parcial = df.copy()

# loc: linhas de índice 0 a 5 (inclusive) e apenas as colunas informadas pelo nome
parcial_loc = df_parcial.loc[0:5, ['nome_municipio', 'uf', 'temp_media_jan', 'ppt_jan']]
display(parcial_loc)

# iloc: linhas nas posições 0 a 5 (0:6, o 6 não entra) e colunas nas posições 0 a 2
parcial_iloc = df_parcial.iloc[0:6, 0:3]
display(parcial_iloc)

          nome_municipio  uf  temp_media_jan  ppt_jan
0  Alta Floresta D'Oeste  RO           25.18   259.78
1              Ariquemes  RO           25.29   334.41
2                 Cabixi  RO           25.85   314.01
3                 Cacoal  RO           24.69   373.13
4             Cerejeiras  RO           25.84   295.31
5      Colorado do Oeste  RO           25.07   322.10

   codigo_ibge         nome_municipio  uf
0      1100015  Alta Floresta D'Oeste  RO
1      1100023              Ariquemes  RO
2      1100031                 Cabixi  RO
3      1100049                 Cacoal  RO
4      1100056             Cerejeiras  RO
5      1100064      Colorado do Oeste  RO

# Como agrupar valores de uma coluna. Semelhante a banco de dados: Groupby

In [26]:
'''
Comandos para agrupar valores de uma coluna (groupby), parecido com GROUP BY do SQL.
groupby('coluna') -> agrupa as linhas que têm o mesmo valor nessa coluna
Depois do groupby, aplicamos uma função de agregação: mean(), sum(), count(), etc.
agg({...}) -> permite aplicar funções diferentes para colunas diferentes de uma vez
Info: Gabriel
'''

# Trabalhamos em uma cópia do dataframe original
df_group = df.copy()

# Agrupa por UF e calcula a média da temperatura média de janeiro em cada estado
media_temp_uf = df_group.groupby('uf')['temp_media_jan'].mean()
display(media_temp_uf)

# Agrupa por UF e conta quantos municípios existem em cada estado
qtd_municipios_uf = df_group.groupby('uf')['nome_municipio'].count()
display(qtd_municipios_uf)

# agg() permite aplicar VÁRIAS funções/colunas diferentes na mesma linha de código
resumo_uf = df_group.groupby('uf').agg({
    'temp_media_jan': 'mean',   # média da temperatura de janeiro
    'ppt_jan': 'sum',           # soma da precipitação de janeiro
    'nome_municipio': 'count'   # quantidade de municípios
})
display(resumo_uf.head())

uf
AC    25.833636
AL    25.767745
AM    26.576129
AP    25.998125
BA    24.734796
CE    26.676630
DF    21.880000
ES    24.444103
GO    24.049797
MA    26.528249
MG    23.020258
MS    25.643671
MT    25.319504
PA    26.153542
PB    25.510628
PE    24.600163
PI    26.694554
PR    23.128521
RJ    24.424457
RN    26.887305
RO    25.107692
RR    26.682000
RS    23.581972
SC    22.223288
SE    26.198000
SP    23.794698
TO    25.370432
Name: temp_media_jan, dtype: float64

uf
AC     22
AL    102
AM     62
AP     16
BA    417
CE    184
DF      1
ES     78
GO    246
MA    217
MG    853
MS     79
MT    141
PA    144
PB    223
PE    185
PI    224
PR    399
RJ     92
RN    167
RO     52
RR     15
RS    497
SC    295
SE     75
SP    645
TO    139
Name: nome_municipio, dtype: int64

    temp_media_jan   ppt_jan  nome_municipio
uf
AC       25.833636   5558.84              22
AL       25.767745   4849.91             102
AM       26.576129  17586.88              62
AP       25.998125   4168.62              16
BA       24.734796  42413.81             417

# Criar um dataframe a partir de um dicionário

In [27]:
'''
Como criar um dataframe a partir de um dicionário (sem precisar de um arquivo csv).
Forma 1: dicionário onde cada CHAVE vira uma coluna e cada VALOR é uma lista com os dados
Forma 2: lista de dicionários, onde cada dicionário representa uma LINHA
Info: Gabriel
'''

# Forma 1: dicionário de listas -> cada chave é uma coluna, cada lista são os valores
# Todas as listas precisam ter o MESMO tamanho (mesma quantidade de linhas)
dados_uf = {
    'uf': ['RS', 'SC', 'PR'],
    'capital': ['Porto Alegre', 'Florianópolis', 'Curitiba'],
    'regiao': ['Sul', 'Sul', 'Sul']
}
df_uf = pd.DataFrame(dados_uf)
display(df_uf)

# Forma 2: lista de dicionários -> cada dicionário vira uma linha do dataframe
dados_linhas = [
    {'uf': 'RS', 'capital': 'Porto Alegre', 'regiao': 'Sul'},
    {'uf': 'SC', 'capital': 'Florianópolis', 'regiao': 'Sul'},
    {'uf': 'PR', 'capital': 'Curitiba', 'regiao': 'Sul'}
]
df_uf_linhas = pd.DataFrame(dados_linhas)
display(df_uf_linhas)

   uf        capital regiao
0  RS   Porto Alegre    Sul
1  SC  Florianópolis    Sul
2  PR       Curitiba    Sul

   uf        capital regiao
0  RS   Porto Alegre    Sul
1  SC  Florianópolis    Sul
2  PR       Curitiba    Sul

# Como deletar linhas com valores vazios

In [28]:
'''
Comandos para deletar linhas com valores vazios (NaN).
dropna() -> remove as linhas que têm PELO MENOS UM valor vazio
subset=[...] -> considera valores vazios apenas nas colunas informadas
how='all' -> só remove a linha se TODAS as colunas estiverem vazias
Info: Gabriel
'''

# Trabalhamos em uma cópia do dataframe original
df_na = df.copy()

# O dataset original não tem valores vazios, então criamos alguns artificialmente
# apenas para demonstrar o funcionamento do dropna()
df_na.loc[0, 'temp_media_jan'] = None
df_na.loc[1, 'ppt_jan'] = None
print('Linhas antes de remover valores vazios:', df_na.shape[0])

# dropna() remove QUALQUER linha que tenha pelo menos uma célula vazia
df_sem_na = df_na.dropna()
print('Linhas após dropna() padrão:', df_sem_na.shape[0])

# subset=[...] limita a verificação a colunas específicas
# aqui só removemos a linha se 'temp_media_jan' estiver vazia (ignora as demais colunas)
df_sem_na_subset = df_na.dropna(subset=['temp_media_jan'])
print('Linhas após dropna(subset=["temp_media_jan"]):', df_sem_na_subset.shape[0])

Linhas antes de remover valores vazios: 5570
Linhas após dropna() padrão: 5567
Linhas após dropna(subset=["temp_media_jan"]): 5568

# Como preencher valores vazios

In [29]:
'''
Comandos para preencher valores vazios (NaN), em vez de simplesmente apagá-los.
fillna(valor) -> substitui os valores vazios por um valor fixo
fillna(df['coluna'].mean()) -> substitui pela média da própria coluna
ffill() -> preenche com o valor da linha ANTERIOR (forward fill)
bfill() -> preenche com o valor da linha SEGUINTE (backward fill)
Info: Gabriel
'''

# Trabalhamos em uma cópia do dataframe original
df_fill = df.copy()

# O dataset original não tem valores vazios, então criamos alguns artificialmente
df_fill.loc[0, 'temp_media_jan'] = None
df_fill.loc[2, 'temp_media_jan'] = None

# Forma 1: preencher com um valor fixo (ex: zero)
df_fill_zero = df_fill['temp_media_jan'].fillna(0)
print('Preenchido com 0:', df_fill_zero.head(3).tolist())

# Forma 2: preencher com a MÉDIA da própria coluna (mais comum em dados numéricos)
media_col = df_fill['temp_media_jan'].mean()
df_fill_media = df_fill['temp_media_jan'].fillna(media_col)
print('Preenchido com a média (%.2f):' % media_col, df_fill_media.head(3).tolist())

# Forma 3: ffill() repete o último valor válido visto antes da lacuna
df_fill_ffill = df_fill['temp_media_jan'].ffill()
print('Preenchido com ffill:', df_fill_ffill.head(3).tolist())

Preenchido com 0: [0.0, 25.29, 0.0]
Preenchido com a média (24.43): [24.43203880007185, 25.29, 24.43203880007185]
Preenchido com ffill: [nan, 25.29, 25.29]

# Comandos para inserir colunas de peso e altura no sistema universal

In [30]:
'''
Comandos para inserir colunas de peso e altura no sistema universal (métrico).
Aqui simulamos um pequeno dataframe com peso em libras (lb) e altura em polegadas (in),
unidades do sistema imperial, e criamos colunas novas convertidas para o sistema
métrico (universal): quilogramas (kg) e centímetros (cm).
1 libra (lb)   = 0.453592 kg
1 polegada (in) = 2.54 cm
Info: Gabriel
'''

# Dataframe de exemplo, criado a partir de um dicionário (visto na célula anterior)
dados_pessoas = {
    'nome': ['Ana', 'Bruno', 'Carla'],
    'peso_lb': [130, 180, 150],     # peso em libras
    'altura_in': [64, 70, 66]       # altura em polegadas
}
df_pessoas = pd.DataFrame(dados_pessoas)

# Cria a coluna de peso no sistema universal (kg), convertendo a partir de libras
df_pessoas['peso_kg'] = df_pessoas['peso_lb'] * 0.453592

# Cria a coluna de altura no sistema universal (cm), convertendo a partir de polegadas
df_pessoas['altura_cm'] = df_pessoas['altura_in'] * 2.54

# Arredonda os valores convertidos para 1 casa decimal, só para facilitar a leitura
df_pessoas['peso_kg'] = df_pessoas['peso_kg'].round(1)
df_pessoas['altura_cm'] = df_pessoas['altura_cm'].round(1)

display(df_pessoas)

    nome  peso_lb  altura_in  peso_kg  altura_cm
0    Ana      130         64     59.0      162.6
1  Bruno      180         70     81.6      177.8
2  Carla      150         66     68.0      167.6